# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pipecpuGUI.ui'
#
# Created: Wed May 27 11:07:40 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Pipeline_CPU(object):
    def setupUi(self, Pipeline_CPU):
        Pipeline_CPU.setObjectName(_fromUtf8("Pipeline_CPU"))
        Pipeline_CPU.resize(1047, 758)
        self.gridLayout_3 = QtGui.QGridLayout(Pipeline_CPU)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(Pipeline_CPU)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(258, 21))
        self.label.setMaximumSize(QtCore.QSize(258, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setScaledContents(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 3)
        self.instructionInput = QtGui.QTextEdit(Pipeline_CPU)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.instructionInput.sizePolicy().hasHeightForWidth())
        self.instructionInput.setSizePolicy(sizePolicy)
        self.instructionInput.setMinimumSize(QtCore.QSize(261, 321))
        self.instructionInput.setMaximumSize(QtCore.QSize(261, 321))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(11)
        self.instructionInput.setFont(font)
        self.instructionInput.setObjectName(_fromUtf8("instructionInput"))
        self.gridLayout.addWidget(self.instructionInput, 1, 0, 1, 3)
        self.StartButton = QtGui.QPushButton(Pipeline_CPU)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StartButton.sizePolicy().hasHeightForWidth())
        self.StartButton.setSizePolicy(sizePolicy)
        self.StartButton.setMinimumSize(QtCore.QSize(82, 27))
        self.StartButton.setMaximumSize(QtCore.QSize(83, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.StartButton.setFont(font)
        self.StartButton.setObjectName(_fromUtf8("StartButton"))
        self.gridLayout.addWidget(self.StartButton, 2, 0, 1, 1)
        self.NextstepButton = QtGui.QPushButton(Pipeline_CPU)
        self.NextstepButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NextstepButton.sizePolicy().hasHeightForWidth())
        self.NextstepButton.setSizePolicy(sizePolicy)
        self.NextstepButton.setMinimumSize(QtCore.QSize(82, 27))
        self.NextstepButton.setMaximumSize(QtCore.QSize(83, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.NextstepButton.setFont(font)
        self.NextstepButton.setObjectName(_fromUtf8("NextstepButton"))
        self.gridLayout.addWidget(self.NextstepButton, 2, 1, 1, 1)
        self.ResetButton = QtGui.QPushButton(Pipeline_CPU)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ResetButton.sizePolicy().hasHeightForWidth())
        self.ResetButton.setSizePolicy(sizePolicy)
        self.ResetButton.setMinimumSize(QtCore.QSize(82, 27))
        self.ResetButton.setMaximumSize(QtCore.QSize(83, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.ResetButton.setFont(font)
        self.ResetButton.setObjectName(_fromUtf8("ResetButton"))
        self.gridLayout.addWidget(self.ResetButton, 2, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 2, 1)
        self.Picture = QtGui.QLabel(Pipeline_CPU)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Picture.sizePolicy().hasHeightForWidth())
        self.Picture.setSizePolicy(sizePolicy)
        self.Picture.setMinimumSize(QtCore.QSize(561, 331))
        self.Picture.setStyleSheet(_fromUtf8("image:url(:/newPrefix/pipeline.jpg)"))
        self.Picture.setText(_fromUtf8(""))
        self.Picture.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Picture.setObjectName(_fromUtf8("Picture"))
        self.gridLayout_2.addWidget(self.Picture, 0, 1, 1, 3)
        self.label_2 = QtGui.QLabel(Pipeline_CPU)
        self.label_2.setMinimumSize(QtCore.QSize(381, 0))
        self.label_2.setText(_fromUtf8(""))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 1, 1, 1, 1)
        self.label_clk = QtGui.QLabel(Pipeline_CPU)
        self.label_clk.setMinimumSize(QtCore.QSize(81, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(14)
        self.label_clk.setFont(font)
        self.label_clk.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_clk.setObjectName(_fromUtf8("label_clk"))
        self.gridLayout_2.addWidget(self.label_clk, 1, 2, 1, 1)
        self.clock = QtGui.QLCDNumber(Pipeline_CPU)
        self.clock.setMinimumSize(QtCore.QSize(81, 31))
        self.clock.setObjectName(_fromUtf8("clock"))
        self.gridLayout_2.addWidget(self.clock, 1, 3, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.IF_stage = QtGui.QGroupBox(Pipeline_CPU)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.IF_stage.sizePolicy().hasHeightForWidth())
        self.IF_stage.setSizePolicy(sizePolicy)
        self.IF_stage.setMinimumSize(QtCore.QSize(136, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(12)
        self.IF_stage.setFont(font)
        self.IF_stage.setAutoFillBackground(False)
        self.IF_stage.setInputMethodHints(QtCore.Qt.ImhNone)
        self.IF_stage.setFlat(False)
        self.IF_stage.setCheckable(False)
        self.IF_stage.setChecked(False)
        self.IF_stage.setObjectName(_fromUtf8("IF_stage"))
        self.gridLayout_5 = QtGui.QGridLayout(self.IF_stage)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.pcounter = QtGui.QHBoxLayout()
        self.pcounter.setObjectName(_fromUtf8("pcounter"))
        self.label_8 = QtGui.QLabel(self.IF_stage)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.pcounter.addWidget(self.label_8)
        self.signalpc = QtGui.QLabel(self.IF_stage)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.signalpc.setFont(font)
        self.signalpc.setText(_fromUtf8(""))
        self.signalpc.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.signalpc.setObjectName(_fromUtf8("signalpc"))
        self.pcounter.addWidget(self.signalpc)
        self.gridLayout_5.addLayout(self.pcounter, 1, 0, 1, 1)
        self.btaken = QtGui.QHBoxLayout()
        self.btaken.setObjectName(_fromUtf8("btaken"))
        self.label_4 = QtGui.QLabel(self.IF_stage)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.btaken.addWidget(self.label_4)
        self.signalbtaken = QtGui.QLabel(self.IF_stage)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.signalbtaken.setFont(font)
        self.signalbtaken.setText(_fromUtf8(""))
        self.signalbtaken.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.signalbtaken.setObjectName(_fromUtf8("signalbtaken"))
        self.btaken.addWidget(self.signalbtaken)
        self.gridLayout_5.addLayout(self.btaken, 2, 0, 1, 1)
        self.wpc = QtGui.QHBoxLayout()
        self.wpc.setObjectName(_fromUtf8("wpc"))
        self.label_5 = QtGui.QLabel(self.IF_stage)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.wpc.addWidget(self.label_5)
        self.signalwpc = QtGui.QLabel(self.IF_stage)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.signalwpc.setFont(font)
        self.signalwpc.setText(_fromUtf8(""))
        self.signalwpc.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.signalwpc.setObjectName(_fromUtf8("signalwpc"))
        self.wpc.addWidget(self.signalwpc)
        self.gridLayout_5.addLayout(self.wpc, 3, 0, 1, 1)
        self.wir = QtGui.QHBoxLayout()
        self.wir.setObjectName(_fromUtf8("wir"))
        self.label_6 = QtGui.QLabel(self.IF_stage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.wir.addWidget(self.label_6)
        self.signalwir = QtGui.QLabel(self.IF_stage)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.signalwir.setFont(font)
        self.signalwir.setText(_fromUtf8(""))
        self.signalwir.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.signalwir.setObjectName(_fromUtf8("signalwir"))
        self.wir.addWidget(self.signalwir)
        self.gridLayout_5.addLayout(self.wir, 4, 0, 1, 1)
        self.ir = QtGui.QHBoxLayout()
        self.ir.setObjectName(_fromUtf8("ir"))
        self.label_13 = QtGui.QLabel(self.IF_stage)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.ir.addWidget(self.label_13)
        self.signalir = QtGui.QLabel(self.IF_stage)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.signalir.setFont(font)
        self.signalir.setText(_fromUtf8(""))
        self.signalir.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.signalir.setObjectName(_fromUtf8("signalir"))
        self.ir.addWidget(self.signalir)
        self.gridLayout_5.addLayout(self.ir, 5, 0, 1, 1)
        self.IF_instruction = QtGui.QLabel(self.IF_stage)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.IF_instruction.setFont(font)
        self.IF_instruction.setText(_fromUtf8(""))
        self.IF_instruction.setObjectName(_fromUtf8("IF_instruction"))
        self.gridLayout_5.addWidget(self.IF_instruction, 0, 0, 1, 1)
        self.horizontalLayout_7.addWidget(self.IF_stage)
        self.ID_stage = QtGui.QGroupBox(Pipeline_CPU)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ID_stage.sizePolicy().hasHeightForWidth())
        self.ID_stage.setSizePolicy(sizePolicy)
        self.ID_stage.setMinimumSize(QtCore.QSize(201, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(12)
        self.ID_stage.setFont(font)
        self.ID_stage.setObjectName(_fromUtf8("ID_stage"))
        self.verticalLayout = QtGui.QVBoxLayout(self.ID_stage)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.ID_instruction = QtGui.QLabel(self.ID_stage)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ID_instruction.setFont(font)
        self.ID_instruction.setText(_fromUtf8(""))
        self.ID_instruction.setObjectName(_fromUtf8("ID_instruction"))
        self.verticalLayout.addWidget(self.ID_instruction)
        self.id_d = QtGui.QHBoxLayout()
        self.id_d.setObjectName(_fromUtf8("id_d"))
        self.label_7 = QtGui.QLabel(self.ID_stage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.id_d.addWidget(self.label_7)
        self.signalid_d = QtGui.QLabel(self.ID_stage)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.signalid_d.setFont(font)
        self.signalid_d.setText(_fromUtf8(""))
        self.signalid_d.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.signalid_d.setObjectName(_fromUtf8("signalid_d"))
        self.id_d.addWidget(self.signalid_d)
        self.verticalLayout.addLayout(self.id_d)
        self.I = QtGui.QHBoxLayout()
        self.I.setObjectName(_fromUtf8("I"))
        self.label_12 = QtGui.QLabel(self.ID_stage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.I.addWidget(self.label_12)
        self.signalI = QtGui.QLabel(self.ID_stage)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.signalI.setFont(font)
        self.signalI.setText(_fromUtf8(""))
        self.signalI.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.signalI.setObjectName(_fromUtf8("signalI"))
        self.I.addWidget(self.signalI)
        self.verticalLayout.addLayout(self.I)
        self.LOADDEPEN = QtGui.QHBoxLayout()
        self.LOADDEPEN.setObjectName(_fromUtf8("LOADDEPEN"))
        self.label_18 = QtGui.QLabel(self.ID_stage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.LOADDEPEN.addWidget(self.label_18)
        self.signalLOADDEPEN = QtGui.QLabel(self.ID_stage)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.signalLOADDEPEN.setFont(font)
        self.signalLOADDEPEN.setText(_fromUtf8(""))
        self.signalLOADDEPEN.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.signalLOADDEPEN.setObjectName(_fromUtf8("signalLOADDEPEN"))
        self.LOADDEPEN.addWidget(self.signalLOADDEPEN)
        self.verticalLayout.addLayout(self.LOADDEPEN)
        self.exe_d_21 = QtGui.QHBoxLayout()
        self.exe_d_21.setObjectName(_fromUtf8("exe_d_21"))
        self.label_61 = QtGui.QLabel(self.ID_stage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.label_61.setFont(font)
        self.label_61.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_61.setObjectName(_fromUtf8("label_61"))
        self.exe_d_21.addWidget(self.label_61)
        self.signalshift = QtGui.QLabel(self.ID_stage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.signalshift.setFont(font)
        self.signalshift.setText(_fromUtf8(""))
        self.signalshift.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.signalshift.setObjectName(_fromUtf8("signalshift"))
        self.exe_d_21.addWidget(self.signalshift)
        self.verticalLayout.addLayout(self.exe_d_21)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.SST = QtGui.QHBoxLayout()
        self.SST.setObjectName(_fromUtf8("SST"))
        self.label_14 = QtGui.QLabel(self.ID_stage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.SST.addWidget(self.label_14)
        self.signalSST = QtGui.QLabel(self.ID_stage)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.signalSST.setFont(font)
        self.signalSST.setText(_fromUtf8(""))
        self.signalSST.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.signalSST.setObjectName(_fromUtf8("signalSST"))
        self.SST.addWidget(self.signalSST)
        self.horizontalLayout_3.addLayout(self.SST)
        self.SEXT = QtGui.QHBoxLayout()
        self.SEXT.setObjectName(_fromUtf8("SEXT"))
        self.label_15 = QtGui.QLabel(self.ID_stage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.SEXT.addWidget(self.label_15)
        self.signalSEXT = QtGui.QLabel(self.ID_stage)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.signalSEXT.setFont(font)
        self.signalSEXT.setText(_fromUtf8(""))
        self.signalSEXT.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.signalSEXT.setObjectName(_fromUtf8("signalSEXT"))
        self.SEXT.addWidget(self.signalSEXT)
        self.horizontalLayout_3.addLayout(self.SEXT)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.A = QtGui.QHBoxLayout()
        self.A.setObjectName(_fromUtf8("A"))
        self.label_10 = QtGui.QLabel(self.ID_stage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.A.addWidget(self.label_10)
        self.signalA = QtGui.QLabel(self.ID_stage)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.signalA.setFont(font)
        self.signalA.setText(_fromUtf8(""))
        self.signalA.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.signalA.setObjectName(_fromUtf8("signalA"))
        self.A.addWidget(self.signalA)
        self.horizontalLayout_6.addLayout(self.A)
        self.B = QtGui.QHBoxLayout()
        self.B.setObjectName(_fromUtf8("B"))
        self.label_11 = QtGui.QLabel(self.ID_stage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.B.addWidget(self.label_11)
        self.signalB = QtGui.QLabel(self.ID_stage)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.signalB.setFont(font)
        self.signalB.setText(_fromUtf8(""))
        self.signalB.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.signalB.setObjectName(_fromUtf8("signalB"))
        self.B.addWidget(self.signalB)
        self.horizontalLayout_6.addLayout(self.B)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.ADEPEN_3 = QtGui.QHBoxLayout()
        self.ADEPEN_3.setObjectName(_fromUtf8("ADEPEN_3"))
        self.label_29 = QtGui.QLabel(self.ID_stage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.label_29.setFont(font)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.ADEPEN_3.addWidget(self.label_29)
        self.signalADEPEN_id = QtGui.QLabel(self.ID_stage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.signalADEPEN_id.setFont(font)
        self.signalADEPEN_id.setText(_fromUtf8(""))
        self.signalADEPEN_id.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.signalADEPEN_id.setObjectName(_fromUtf8("signalADEPEN_id"))
        self.ADEPEN_3.addWidget(self.signalADEPEN_id)
        self.horizontalLayout.addLayout(self.ADEPEN_3)
        self.BDEPEN = QtGui.QHBoxLayout()
        self.BDEPEN.setObjectName(_fromUtf8("BDEPEN"))
        self.label_24 = QtGui.QLabel(self.ID_stage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.BDEPEN.addWidget(self.label_24)
        self.signalBDEPEN_id = QtGui.QLabel(self.ID_stage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.signalBDEPEN_id.setFont(font)
        self.signalBDEPEN_id.setText(_fromUtf8(""))
        self.signalBDEPEN_id.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.signalBDEPEN_id.setObjectName(_fromUtf8("signalBDEPEN_id"))
        self.BDEPEN.addWidget(self.signalBDEPEN_id)
        self.horizontalLayout.addLayout(self.BDEPEN)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.BDEPEN_2 = QtGui.QHBoxLayout()
        self.BDEPEN_2.setObjectName(_fromUtf8("BDEPEN_2"))
        self.label_26 = QtGui.QLabel(self.ID_stage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.label_26.setFont(font)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.BDEPEN_2.addWidget(self.label_26)
        self.signalQDEPEN_id = QtGui.QLabel(self.ID_stage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.signalQDEPEN_id.setFont(font)
        self.signalQDEPEN_id.setText(_fromUtf8(""))
        self.signalQDEPEN_id.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.signalQDEPEN_id.setObjectName(_fromUtf8("signalQDEPEN_id"))
        self.BDEPEN_2.addWidget(self.signalQDEPEN_id)
        self.horizontalLayout_2.addLayout(self.BDEPEN_2)
        self.ALUOP_3 = QtGui.QHBoxLayout()
        self.ALUOP_3.setObjectName(_fromUtf8("ALUOP_3"))
        self.label_30 = QtGui.QLabel(self.ID_stage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.label_30.setFont(font)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.ALUOP_3.addWidget(self.label_30)
        self.signalALUOP_id = QtGui.QLabel(self.ID_stage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.signalALUOP_id.setFont(font)
        self.signalALUOP_id.setText(_fromUtf8(""))
        self.signalALUOP_id.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.signalALUOP_id.setObjectName(_fromUtf8("signalALUOP_id"))
        self.ALUOP_3.addWidget(self.signalALUOP_id)
        self.horizontalLayout_2.addLayout(self.ALUOP_3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.WZ_2 = QtGui.QHBoxLayout()
        self.WZ_2.setObjectName(_fromUtf8("WZ_2"))
        self.label_53 = QtGui.QLabel(self.ID_stage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.label_53.setFont(font)
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.WZ_2.addWidget(self.label_53)
        self.signalWZ_id = QtGui.QLabel(self.ID_stage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.signalWZ_id.setFont(font)
        self.signalWZ_id.setText(_fromUtf8(""))
        self.signalWZ_id.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.signalWZ_id.setObjectName(_fromUtf8("signalWZ_id"))
        self.WZ_2.addWidget(self.signalWZ_id)
        self.horizontalLayout_4.addLayout(self.WZ_2)
        self.exe_d_14 = QtGui.QHBoxLayout()
        self.exe_d_14.setObjectName(_fromUtf8("exe_d_14"))
        self.label_58 = QtGui.QLabel(self.ID_stage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.label_58.setFont(font)
        self.label_58.setObjectName(_fromUtf8("label_58"))
        self.exe_d_14.addWidget(self.label_58)
        self.signalwmem_id = QtGui.QLabel(self.ID_stage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.signalwmem_id.setFont(font)
        self.signalwmem_id.setText(_fromUtf8(""))
        self.signalwmem_id.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.signalwmem_id.setObjectName(_fromUtf8("signalwmem_id"))
        self.exe_d_14.addWidget(self.signalwmem_id)
        self.horizontalLayout_4.addLayout(self.exe_d_14)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.exe_d_19 = QtGui.QHBoxLayout()
        self.exe_d_19.setObjectName(_fromUtf8("exe_d_19"))
        self.label_59 = QtGui.QLabel(self.ID_stage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.label_59.setFont(font)
        self.label_59.setObjectName(_fromUtf8("label_59"))
        self.exe_d_19.addWidget(self.label_59)
        self.signalsld_id = QtGui.QLabel(self.ID_stage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.signalsld_id.setFont(font)
        self.signalsld_id.setText(_fromUtf8(""))
        self.signalsld_id.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.signalsld_id.setObjectName(_fromUtf8("signalsld_id"))
        self.exe_d_19.addWidget(self.signalsld_id)
        self.horizontalLayout_5.addLayout(self.exe_d_19)
        self.exe_d_20 = QtGui.QHBoxLayout()
        self.exe_d_20.setObjectName(_fromUtf8("exe_d_20"))
        self.label_60 = QtGui.QLabel(self.ID_stage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.label_60.setFont(font)
        self.label_60.setObjectName(_fromUtf8("label_60"))
        self.exe_d_20.addWidget(self.label_60)
        self.signalwreg_id = QtGui.QLabel(self.ID_stage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.signalwreg_id.setFont(font)
        self.signalwreg_id.setText(_fromUtf8(""))
        self.signalwreg_id.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.signalwreg_id.setObjectName(_fromUtf8("signalwreg_id"))
        self.exe_d_20.addWidget(self.signalwreg_id)
        self.horizontalLayout_5.addLayout(self.exe_d_20)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7.addWidget(self.ID_stage)
        self.EXE_stage = QtGui.QGroupBox(Pipeline_CPU)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EXE_stage.sizePolicy().hasHeightForWidth())
        self.EXE_stage.setSizePolicy(sizePolicy)
        self.EXE_stage.setMinimumSize(QtCore.QSize(201, 239))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(12)
        self.EXE_stage.setFont(font)
        self.EXE_stage.setObjectName(_fromUtf8("EXE_stage"))
        self.gridLayout_4 = QtGui.QGridLayout(self.EXE_stage)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.S = QtGui.QHBoxLayout()
        self.S.setObjectName(_fromUtf8("S"))
        self.label_22 = QtGui.QLabel(self.EXE_stage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.S.addWidget(self.label_22)
        self.signalS = QtGui.QLabel(self.EXE_stage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.signalS.setFont(font)
        self.signalS.setText(_fromUtf8(""))
        self.signalS.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.signalS.setObjectName(_fromUtf8("signalS"))
        self.S.addWidget(self.signalS)
        self.gridLayout_4.addLayout(self.S, 4, 0, 1, 1)
        self.Z = QtGui.QHBoxLayout()
        self.Z.setObjectName(_fromUtf8("Z"))
        self.label_20 = QtGui.QLabel(self.EXE_stage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.Z.addWidget(self.label_20)
        self.signalz = QtGui.QLabel(self.EXE_stage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.signalz.setFont(font)
        self.signalz.setText(_fromUtf8(""))
        self.signalz.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.signalz.setObjectName(_fromUtf8("signalz"))
        self.Z.addWidget(self.signalz)
        self.gridLayout_4.addLayout(self.Z, 2, 0, 1, 1)
        self.BDEPEN_5 = QtGui.QHBoxLayout()
        self.BDEPEN_5.setObjectName(_fromUtf8("BDEPEN_5"))
        self.label_33 = QtGui.QLabel(self.EXE_stage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.label_33.setFont(font)
        self.label_33.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.BDEPEN_5.addWidget(self.label_33)
        self.signalQDEPEN_exe = QtGui.QLabel(self.EXE_stage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.signalQDEPEN_exe.setFont(font)
        self.signalQDEPEN_exe.setText(_fromUtf8(""))
        self.signalQDEPEN_exe.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.signalQDEPEN_exe.setObjectName(_fromUtf8("signalQDEPEN_exe"))
        self.BDEPEN_5.addWidget(self.signalQDEPEN_exe)
        self.gridLayout_4.addLayout(self.BDEPEN_5, 6, 0, 1, 1)
        self.R = QtGui.QHBoxLayout()
        self.R.setObjectName(_fromUtf8("R"))
        self.label_21 = QtGui.QLabel(self.EXE_stage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.R.addWidget(self.label_21)
        self.signalR = QtGui.QLabel(self.EXE_stage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.signalR.setFont(font)
        self.signalR.setText(_fromUtf8(""))
        self.signalR.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.signalR.setObjectName(_fromUtf8("signalR"))
        self.R.addWidget(self.signalR)
        self.gridLayout_4.addLayout(self.R, 3, 0, 1, 1)
        self.ALUOP = QtGui.QHBoxLayout()
        self.ALUOP.setObjectName(_fromUtf8("ALUOP"))
        self.label_25 = QtGui.QLabel(self.EXE_stage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.ALUOP.addWidget(self.label_25)
        self.signalALUOP = QtGui.QLabel(self.EXE_stage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.signalALUOP.setFont(font)
        self.signalALUOP.setText(_fromUtf8(""))
        self.signalALUOP.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.signalALUOP.setObjectName(_fromUtf8("signalALUOP"))
        self.ALUOP.addWidget(self.signalALUOP)
        self.gridLayout_4.addLayout(self.ALUOP, 7, 0, 1, 1)
        self.exe_d = QtGui.QHBoxLayout()
        self.exe_d.setObjectName(_fromUtf8("exe_d"))
        self.label_19 = QtGui.QLabel(self.EXE_stage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.exe_d.addWidget(self.label_19)
        self.signalexe_d = QtGui.QLabel(self.EXE_stage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.signalexe_d.setFont(font)
        self.signalexe_d.setText(_fromUtf8(""))
        self.signalexe_d.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.signalexe_d.setObjectName(_fromUtf8("signalexe_d"))
        self.exe_d.addWidget(self.signalexe_d)
        self.gridLayout_4.addLayout(self.exe_d, 1, 0, 1, 1)
        self.EXE_instruction = QtGui.QLabel(self.EXE_stage)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.EXE_instruction.setFont(font)
        self.EXE_instruction.setText(_fromUtf8(""))
        self.EXE_instruction.setObjectName(_fromUtf8("EXE_instruction"))
        self.gridLayout_4.addWidget(self.EXE_instruction, 0, 0, 1, 1)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.ADEPEN = QtGui.QHBoxLayout()
        self.ADEPEN.setObjectName(_fromUtf8("ADEPEN"))
        self.label_23 = QtGui.QLabel(self.EXE_stage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.ADEPEN.addWidget(self.label_23)
        self.signalADEPEN = QtGui.QLabel(self.EXE_stage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.signalADEPEN.setFont(font)
        self.signalADEPEN.setText(_fromUtf8(""))
        self.signalADEPEN.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.signalADEPEN.setObjectName(_fromUtf8("signalADEPEN"))
        self.ADEPEN.addWidget(self.signalADEPEN)
        self.horizontalLayout_11.addLayout(self.ADEPEN)
        self.BDEPEN_3 = QtGui.QHBoxLayout()
        self.BDEPEN_3.setObjectName(_fromUtf8("BDEPEN_3"))
        self.label_31 = QtGui.QLabel(self.EXE_stage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.label_31.setFont(font)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.BDEPEN_3.addWidget(self.label_31)
        self.signalBDEPEN = QtGui.QLabel(self.EXE_stage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.signalBDEPEN.setFont(font)
        self.signalBDEPEN.setText(_fromUtf8(""))
        self.signalBDEPEN.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.signalBDEPEN.setObjectName(_fromUtf8("signalBDEPEN"))
        self.BDEPEN_3.addWidget(self.signalBDEPEN)
        self.horizontalLayout_11.addLayout(self.BDEPEN_3)
        self.gridLayout_4.addLayout(self.horizontalLayout_11, 8, 0, 1, 1)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.WZ = QtGui.QHBoxLayout()
        self.WZ.setObjectName(_fromUtf8("WZ"))
        self.label_40 = QtGui.QLabel(self.EXE_stage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.label_40.setFont(font)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.WZ.addWidget(self.label_40)
        self.signalWZ = QtGui.QLabel(self.EXE_stage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.signalWZ.setFont(font)
        self.signalWZ.setText(_fromUtf8(""))
        self.signalWZ.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.signalWZ.setObjectName(_fromUtf8("signalWZ"))
        self.WZ.addWidget(self.signalWZ)
        self.horizontalLayout_12.addLayout(self.WZ)
        self.exe_d_24 = QtGui.QHBoxLayout()
        self.exe_d_24.setObjectName(_fromUtf8("exe_d_24"))
        self.label_65 = QtGui.QLabel(self.EXE_stage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.label_65.setFont(font)
        self.label_65.setObjectName(_fromUtf8("label_65"))
        self.exe_d_24.addWidget(self.label_65)
        self.signalwmem_exe = QtGui.QLabel(self.EXE_stage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.signalwmem_exe.setFont(font)
        self.signalwmem_exe.setText(_fromUtf8(""))
        self.signalwmem_exe.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.signalwmem_exe.setObjectName(_fromUtf8("signalwmem_exe"))
        self.exe_d_24.addWidget(self.signalwmem_exe)
        self.horizontalLayout_12.addLayout(self.exe_d_24)
        self.gridLayout_4.addLayout(self.horizontalLayout_12, 9, 0, 1, 1)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.exe_d_23 = QtGui.QHBoxLayout()
        self.exe_d_23.setObjectName(_fromUtf8("exe_d_23"))
        self.label_64 = QtGui.QLabel(self.EXE_stage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.label_64.setFont(font)
        self.label_64.setObjectName(_fromUtf8("label_64"))
        self.exe_d_23.addWidget(self.label_64)
        self.signalsld_exe = QtGui.QLabel(self.EXE_stage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.signalsld_exe.setFont(font)
        self.signalsld_exe.setText(_fromUtf8(""))
        self.signalsld_exe.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.signalsld_exe.setObjectName(_fromUtf8("signalsld_exe"))
        self.exe_d_23.addWidget(self.signalsld_exe)
        self.horizontalLayout_13.addLayout(self.exe_d_23)
        self.exe_d_22 = QtGui.QHBoxLayout()
        self.exe_d_22.setObjectName(_fromUtf8("exe_d_22"))
        self.label_63 = QtGui.QLabel(self.EXE_stage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.label_63.setFont(font)
        self.label_63.setObjectName(_fromUtf8("label_63"))
        self.exe_d_22.addWidget(self.label_63)
        self.signalwreg_exe = QtGui.QLabel(self.EXE_stage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.signalwreg_exe.setFont(font)
        self.signalwreg_exe.setText(_fromUtf8(""))
        self.signalwreg_exe.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.signalwreg_exe.setObjectName(_fromUtf8("signalwreg_exe"))
        self.exe_d_22.addWidget(self.signalwreg_exe)
        self.horizontalLayout_13.addLayout(self.exe_d_22)
        self.gridLayout_4.addLayout(self.horizontalLayout_13, 10, 0, 1, 1)
        self.horizontalLayout_7.addWidget(self.EXE_stage)
        self.MEM_stage = QtGui.QGroupBox(Pipeline_CPU)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MEM_stage.sizePolicy().hasHeightForWidth())
        self.MEM_stage.setSizePolicy(sizePolicy)
        self.MEM_stage.setMinimumSize(QtCore.QSize(136, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(12)
        self.MEM_stage.setFont(font)
        self.MEM_stage.setObjectName(_fromUtf8("MEM_stage"))
        self.gridLayout_9 = QtGui.QGridLayout(self.MEM_stage)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.MEM_instruction = QtGui.QLabel(self.MEM_stage)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.MEM_instruction.setFont(font)
        self.MEM_instruction.setText(_fromUtf8(""))
        self.MEM_instruction.setObjectName(_fromUtf8("MEM_instruction"))
        self.gridLayout_9.addWidget(self.MEM_instruction, 0, 0, 1, 1)
        self.exe_d_2 = QtGui.QHBoxLayout()
        self.exe_d_2.setObjectName(_fromUtf8("exe_d_2"))
        self.label_41 = QtGui.QLabel(self.MEM_stage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.label_41.setFont(font)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.exe_d_2.addWidget(self.label_41)
        self.signalmem_d = QtGui.QLabel(self.MEM_stage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.signalmem_d.setFont(font)
        self.signalmem_d.setText(_fromUtf8(""))
        self.signalmem_d.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.signalmem_d.setObjectName(_fromUtf8("signalmem_d"))
        self.exe_d_2.addWidget(self.signalmem_d)
        self.gridLayout_9.addLayout(self.exe_d_2, 1, 0, 1, 1)
        self.exe_d_3 = QtGui.QHBoxLayout()
        self.exe_d_3.setObjectName(_fromUtf8("exe_d_3"))
        self.label_42 = QtGui.QLabel(self.MEM_stage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.label_42.setFont(font)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.exe_d_3.addWidget(self.label_42)
        self.signalD = QtGui.QLabel(self.MEM_stage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.signalD.setFont(font)
        self.signalD.setText(_fromUtf8(""))
        self.signalD.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.signalD.setObjectName(_fromUtf8("signalD"))
        self.exe_d_3.addWidget(self.signalD)
        self.gridLayout_9.addLayout(self.exe_d_3, 2, 0, 1, 1)
        self.exe_d_4 = QtGui.QHBoxLayout()
        self.exe_d_4.setObjectName(_fromUtf8("exe_d_4"))
        self.label_43 = QtGui.QLabel(self.MEM_stage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.label_43.setFont(font)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.exe_d_4.addWidget(self.label_43)
        self.signalC = QtGui.QLabel(self.MEM_stage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.signalC.setFont(font)
        self.signalC.setText(_fromUtf8(""))
        self.signalC.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.signalC.setObjectName(_fromUtf8("signalC"))
        self.exe_d_4.addWidget(self.signalC)
        self.gridLayout_9.addLayout(self.exe_d_4, 3, 0, 1, 1)
        self.exe_d_5 = QtGui.QHBoxLayout()
        self.exe_d_5.setObjectName(_fromUtf8("exe_d_5"))
        self.label_44 = QtGui.QLabel(self.MEM_stage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.label_44.setFont(font)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.exe_d_5.addWidget(self.label_44)
        self.signalwmem = QtGui.QLabel(self.MEM_stage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.signalwmem.setFont(font)
        self.signalwmem.setText(_fromUtf8(""))
        self.signalwmem.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.signalwmem.setObjectName(_fromUtf8("signalwmem"))
        self.exe_d_5.addWidget(self.signalwmem)
        self.gridLayout_9.addLayout(self.exe_d_5, 5, 0, 1, 1)
        self.exe_d_25 = QtGui.QHBoxLayout()
        self.exe_d_25.setObjectName(_fromUtf8("exe_d_25"))
        self.label_66 = QtGui.QLabel(self.MEM_stage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.label_66.setFont(font)
        self.label_66.setObjectName(_fromUtf8("label_66"))
        self.exe_d_25.addWidget(self.label_66)
        self.signalsld_mem = QtGui.QLabel(self.MEM_stage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.signalsld_mem.setFont(font)
        self.signalsld_mem.setText(_fromUtf8(""))
        self.signalsld_mem.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.signalsld_mem.setObjectName(_fromUtf8("signalsld_mem"))
        self.exe_d_25.addWidget(self.signalsld_mem)
        self.gridLayout_9.addLayout(self.exe_d_25, 6, 0, 1, 1)
        self.exe_d_26 = QtGui.QHBoxLayout()
        self.exe_d_26.setObjectName(_fromUtf8("exe_d_26"))
        self.label_67 = QtGui.QLabel(self.MEM_stage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.label_67.setFont(font)
        self.label_67.setObjectName(_fromUtf8("label_67"))
        self.exe_d_26.addWidget(self.label_67)
        self.signalwreg_mem = QtGui.QLabel(self.MEM_stage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.signalwreg_mem.setFont(font)
        self.signalwreg_mem.setText(_fromUtf8(""))
        self.signalwreg_mem.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.signalwreg_mem.setObjectName(_fromUtf8("signalwreg_mem"))
        self.exe_d_26.addWidget(self.signalwreg_mem)
        self.gridLayout_9.addLayout(self.exe_d_26, 7, 0, 1, 1)
        self.exe_d_27 = QtGui.QHBoxLayout()
        self.exe_d_27.setObjectName(_fromUtf8("exe_d_27"))
        self.address = QtGui.QLabel(self.MEM_stage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.address.setFont(font)
        self.address.setText(_fromUtf8(""))
        self.address.setObjectName(_fromUtf8("address"))
        self.exe_d_27.addWidget(self.address)
        self.addr_value = QtGui.QLabel(self.MEM_stage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.addr_value.setFont(font)
        self.addr_value.setText(_fromUtf8(""))
        self.addr_value.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.addr_value.setObjectName(_fromUtf8("addr_value"))
        self.exe_d_27.addWidget(self.addr_value)
        self.gridLayout_9.addLayout(self.exe_d_27, 8, 0, 1, 1)
        self.BDEPEN_6 = QtGui.QHBoxLayout()
        self.BDEPEN_6.setObjectName(_fromUtf8("BDEPEN_6"))
        self.label_34 = QtGui.QLabel(self.MEM_stage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.label_34.setFont(font)
        self.label_34.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.BDEPEN_6.addWidget(self.label_34)
        self.signalQDEPEN = QtGui.QLabel(self.MEM_stage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.signalQDEPEN.setFont(font)
        self.signalQDEPEN.setText(_fromUtf8(""))
        self.signalQDEPEN.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.signalQDEPEN.setObjectName(_fromUtf8("signalQDEPEN"))
        self.BDEPEN_6.addWidget(self.signalQDEPEN)
        self.gridLayout_9.addLayout(self.BDEPEN_6, 4, 0, 1, 1)
        self.horizontalLayout_7.addWidget(self.MEM_stage)
        self.WB_stage = QtGui.QGroupBox(Pipeline_CPU)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WB_stage.sizePolicy().hasHeightForWidth())
        self.WB_stage.setSizePolicy(sizePolicy)
        self.WB_stage.setMinimumSize(QtCore.QSize(136, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(12)
        self.WB_stage.setFont(font)
        self.WB_stage.setObjectName(_fromUtf8("WB_stage"))
        self.gridLayout_7 = QtGui.QGridLayout(self.WB_stage)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.exe_d_7 = QtGui.QHBoxLayout()
        self.exe_d_7.setObjectName(_fromUtf8("exe_d_7"))
        self.label_46 = QtGui.QLabel(self.WB_stage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.label_46.setFont(font)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.exe_d_7.addWidget(self.label_46)
        self.signalSLD = QtGui.QLabel(self.WB_stage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.signalSLD.setFont(font)
        self.signalSLD.setText(_fromUtf8(""))
        self.signalSLD.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.signalSLD.setObjectName(_fromUtf8("signalSLD"))
        self.exe_d_7.addWidget(self.signalSLD)
        self.gridLayout_7.addLayout(self.exe_d_7, 1, 0, 1, 1)
        self.exe_d_8 = QtGui.QHBoxLayout()
        self.exe_d_8.setObjectName(_fromUtf8("exe_d_8"))
        self.label_47 = QtGui.QLabel(self.WB_stage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.label_47.setFont(font)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.exe_d_8.addWidget(self.label_47)
        self.signalWREG = QtGui.QLabel(self.WB_stage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.signalWREG.setFont(font)
        self.signalWREG.setText(_fromUtf8(""))
        self.signalWREG.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.signalWREG.setObjectName(_fromUtf8("signalWREG"))
        self.exe_d_8.addWidget(self.signalWREG)
        self.gridLayout_7.addLayout(self.exe_d_8, 2, 0, 1, 1)
        self.WB_instruction = QtGui.QLabel(self.WB_stage)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.WB_instruction.setFont(font)
        self.WB_instruction.setText(_fromUtf8(""))
        self.WB_instruction.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.WB_instruction.setObjectName(_fromUtf8("WB_instruction"))
        self.gridLayout_7.addWidget(self.WB_instruction, 0, 0, 1, 1)
        self.horizontalLayout_7.addWidget(self.WB_stage)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.Registers = QtGui.QGroupBox(Pipeline_CPU)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Registers.sizePolicy().hasHeightForWidth())
        self.Registers.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(12)
        self.Registers.setFont(font)
        self.Registers.setObjectName(_fromUtf8("Registers"))
        self.gridLayout_6 = QtGui.QGridLayout(self.Registers)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.exe_d_6 = QtGui.QHBoxLayout()
        self.exe_d_6.setObjectName(_fromUtf8("exe_d_6"))
        self.label_45 = QtGui.QLabel(self.Registers)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.label_45.setFont(font)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.exe_d_6.addWidget(self.label_45)
        self.register0 = QtGui.QLabel(self.Registers)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.register0.setFont(font)
        self.register0.setText(_fromUtf8(""))
        self.register0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.register0.setObjectName(_fromUtf8("register0"))
        self.exe_d_6.addWidget(self.register0)
        self.horizontalLayout_8.addLayout(self.exe_d_6)
        self.exe_d_34 = QtGui.QHBoxLayout()
        self.exe_d_34.setObjectName(_fromUtf8("exe_d_34"))
        self.label_73 = QtGui.QLabel(self.Registers)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.label_73.setFont(font)
        self.label_73.setObjectName(_fromUtf8("label_73"))
        self.exe_d_34.addWidget(self.label_73)
        self.register16 = QtGui.QLabel(self.Registers)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.register16.setFont(font)
        self.register16.setText(_fromUtf8(""))
        self.register16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.register16.setObjectName(_fromUtf8("register16"))
        self.exe_d_34.addWidget(self.register16)
        self.horizontalLayout_8.addLayout(self.exe_d_34)
        self.gridLayout_6.addLayout(self.horizontalLayout_8, 0, 0, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.exe_d_9 = QtGui.QHBoxLayout()
        self.exe_d_9.setObjectName(_fromUtf8("exe_d_9"))
        self.label_48 = QtGui.QLabel(self.Registers)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.label_48.setFont(font)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.exe_d_9.addWidget(self.label_48)
        self.register1 = QtGui.QLabel(self.Registers)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.register1.setFont(font)
        self.register1.setText(_fromUtf8(""))
        self.register1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.register1.setObjectName(_fromUtf8("register1"))
        self.exe_d_9.addWidget(self.register1)
        self.horizontalLayout_9.addLayout(self.exe_d_9)
        self.exe_d_36 = QtGui.QHBoxLayout()
        self.exe_d_36.setObjectName(_fromUtf8("exe_d_36"))
        self.label_75 = QtGui.QLabel(self.Registers)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.label_75.setFont(font)
        self.label_75.setObjectName(_fromUtf8("label_75"))
        self.exe_d_36.addWidget(self.label_75)
        self.register17 = QtGui.QLabel(self.Registers)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.register17.setFont(font)
        self.register17.setText(_fromUtf8(""))
        self.register17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.register17.setObjectName(_fromUtf8("register17"))
        self.exe_d_36.addWidget(self.register17)
        self.horizontalLayout_9.addLayout(self.exe_d_36)
        self.gridLayout_6.addLayout(self.horizontalLayout_9, 1, 0, 1, 1)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.exe_d_10 = QtGui.QHBoxLayout()
        self.exe_d_10.setObjectName(_fromUtf8("exe_d_10"))
        self.label_49 = QtGui.QLabel(self.Registers)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.label_49.setFont(font)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.exe_d_10.addWidget(self.label_49)
        self.register2 = QtGui.QLabel(self.Registers)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.register2.setFont(font)
        self.register2.setText(_fromUtf8(""))
        self.register2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.register2.setObjectName(_fromUtf8("register2"))
        self.exe_d_10.addWidget(self.register2)
        self.horizontalLayout_10.addLayout(self.exe_d_10)
        self.exe_d_37 = QtGui.QHBoxLayout()
        self.exe_d_37.setObjectName(_fromUtf8("exe_d_37"))
        self.label_76 = QtGui.QLabel(self.Registers)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.label_76.setFont(font)
        self.label_76.setObjectName(_fromUtf8("label_76"))
        self.exe_d_37.addWidget(self.label_76)
        self.register18 = QtGui.QLabel(self.Registers)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.register18.setFont(font)
        self.register18.setText(_fromUtf8(""))
        self.register18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.register18.setObjectName(_fromUtf8("register18"))
        self.exe_d_37.addWidget(self.register18)
        self.horizontalLayout_10.addLayout(self.exe_d_37)
        self.gridLayout_6.addLayout(self.horizontalLayout_10, 2, 0, 1, 1)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.exe_d_11 = QtGui.QHBoxLayout()
        self.exe_d_11.setObjectName(_fromUtf8("exe_d_11"))
        self.label_50 = QtGui.QLabel(self.Registers)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.label_50.setFont(font)
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.exe_d_11.addWidget(self.label_50)
        self.register3 = QtGui.QLabel(self.Registers)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.register3.setFont(font)
        self.register3.setText(_fromUtf8(""))
        self.register3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.register3.setObjectName(_fromUtf8("register3"))
        self.exe_d_11.addWidget(self.register3)
        self.horizontalLayout_14.addLayout(self.exe_d_11)
        self.exe_d_38 = QtGui.QHBoxLayout()
        self.exe_d_38.setObjectName(_fromUtf8("exe_d_38"))
        self.label_77 = QtGui.QLabel(self.Registers)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.label_77.setFont(font)
        self.label_77.setObjectName(_fromUtf8("label_77"))
        self.exe_d_38.addWidget(self.label_77)
        self.register19 = QtGui.QLabel(self.Registers)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.register19.setFont(font)
        self.register19.setText(_fromUtf8(""))
        self.register19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.register19.setObjectName(_fromUtf8("register19"))
        self.exe_d_38.addWidget(self.register19)
        self.horizontalLayout_14.addLayout(self.exe_d_38)
        self.gridLayout_6.addLayout(self.horizontalLayout_14, 3, 0, 1, 1)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.exe_d_12 = QtGui.QHBoxLayout()
        self.exe_d_12.setObjectName(_fromUtf8("exe_d_12"))
        self.label_51 = QtGui.QLabel(self.Registers)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.label_51.setFont(font)
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.exe_d_12.addWidget(self.label_51)
        self.register4 = QtGui.QLabel(self.Registers)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.register4.setFont(font)
        self.register4.setText(_fromUtf8(""))
        self.register4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.register4.setObjectName(_fromUtf8("register4"))
        self.exe_d_12.addWidget(self.register4)
        self.horizontalLayout_15.addLayout(self.exe_d_12)
        self.exe_d_39 = QtGui.QHBoxLayout()
        self.exe_d_39.setObjectName(_fromUtf8("exe_d_39"))
        self.label_78 = QtGui.QLabel(self.Registers)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.label_78.setFont(font)
        self.label_78.setObjectName(_fromUtf8("label_78"))
        self.exe_d_39.addWidget(self.label_78)
        self.register20 = QtGui.QLabel(self.Registers)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.register20.setFont(font)
        self.register20.setText(_fromUtf8(""))
        self.register20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.register20.setObjectName(_fromUtf8("register20"))
        self.exe_d_39.addWidget(self.register20)
        self.horizontalLayout_15.addLayout(self.exe_d_39)
        self.gridLayout_6.addLayout(self.horizontalLayout_15, 4, 0, 1, 1)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.exe_d_13 = QtGui.QHBoxLayout()
        self.exe_d_13.setObjectName(_fromUtf8("exe_d_13"))
        self.label_52 = QtGui.QLabel(self.Registers)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.label_52.setFont(font)
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.exe_d_13.addWidget(self.label_52)
        self.register5 = QtGui.QLabel(self.Registers)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.register5.setFont(font)
        self.register5.setText(_fromUtf8(""))
        self.register5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.register5.setObjectName(_fromUtf8("register5"))
        self.exe_d_13.addWidget(self.register5)
        self.horizontalLayout_16.addLayout(self.exe_d_13)
        self.exe_d_40 = QtGui.QHBoxLayout()
        self.exe_d_40.setObjectName(_fromUtf8("exe_d_40"))
        self.label_79 = QtGui.QLabel(self.Registers)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.label_79.setFont(font)
        self.label_79.setObjectName(_fromUtf8("label_79"))
        self.exe_d_40.addWidget(self.label_79)
        self.register21 = QtGui.QLabel(self.Registers)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.register21.setFont(font)
        self.register21.setText(_fromUtf8(""))
        self.register21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.register21.setObjectName(_fromUtf8("register21"))
        self.exe_d_40.addWidget(self.register21)
        self.horizontalLayout_16.addLayout(self.exe_d_40)
        self.gridLayout_6.addLayout(self.horizontalLayout_16, 5, 0, 1, 1)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.exe_d_15 = QtGui.QHBoxLayout()
        self.exe_d_15.setObjectName(_fromUtf8("exe_d_15"))
        self.label_54 = QtGui.QLabel(self.Registers)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.label_54.setFont(font)
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.exe_d_15.addWidget(self.label_54)
        self.register6 = QtGui.QLabel(self.Registers)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.register6.setFont(font)
        self.register6.setText(_fromUtf8(""))
        self.register6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.register6.setObjectName(_fromUtf8("register6"))
        self.exe_d_15.addWidget(self.register6)
        self.horizontalLayout_17.addLayout(self.exe_d_15)
        self.exe_d_41 = QtGui.QHBoxLayout()
        self.exe_d_41.setObjectName(_fromUtf8("exe_d_41"))
        self.label_80 = QtGui.QLabel(self.Registers)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.label_80.setFont(font)
        self.label_80.setObjectName(_fromUtf8("label_80"))
        self.exe_d_41.addWidget(self.label_80)
        self.register22 = QtGui.QLabel(self.Registers)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.register22.setFont(font)
        self.register22.setText(_fromUtf8(""))
        self.register22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.register22.setObjectName(_fromUtf8("register22"))
        self.exe_d_41.addWidget(self.register22)
        self.horizontalLayout_17.addLayout(self.exe_d_41)
        self.gridLayout_6.addLayout(self.horizontalLayout_17, 6, 0, 1, 1)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.exe_d_16 = QtGui.QHBoxLayout()
        self.exe_d_16.setObjectName(_fromUtf8("exe_d_16"))
        self.label_55 = QtGui.QLabel(self.Registers)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.label_55.setFont(font)
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.exe_d_16.addWidget(self.label_55)
        self.register7 = QtGui.QLabel(self.Registers)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.register7.setFont(font)
        self.register7.setText(_fromUtf8(""))
        self.register7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.register7.setObjectName(_fromUtf8("register7"))
        self.exe_d_16.addWidget(self.register7)
        self.horizontalLayout_18.addLayout(self.exe_d_16)
        self.exe_d_42 = QtGui.QHBoxLayout()
        self.exe_d_42.setObjectName(_fromUtf8("exe_d_42"))
        self.label_81 = QtGui.QLabel(self.Registers)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.label_81.setFont(font)
        self.label_81.setObjectName(_fromUtf8("label_81"))
        self.exe_d_42.addWidget(self.label_81)
        self.register23 = QtGui.QLabel(self.Registers)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.register23.setFont(font)
        self.register23.setText(_fromUtf8(""))
        self.register23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.register23.setObjectName(_fromUtf8("register23"))
        self.exe_d_42.addWidget(self.register23)
        self.horizontalLayout_18.addLayout(self.exe_d_42)
        self.gridLayout_6.addLayout(self.horizontalLayout_18, 7, 0, 1, 1)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.exe_d_17 = QtGui.QHBoxLayout()
        self.exe_d_17.setObjectName(_fromUtf8("exe_d_17"))
        self.label_56 = QtGui.QLabel(self.Registers)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.label_56.setFont(font)
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.exe_d_17.addWidget(self.label_56)
        self.register8 = QtGui.QLabel(self.Registers)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.register8.setFont(font)
        self.register8.setText(_fromUtf8(""))
        self.register8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.register8.setObjectName(_fromUtf8("register8"))
        self.exe_d_17.addWidget(self.register8)
        self.horizontalLayout_19.addLayout(self.exe_d_17)
        self.exe_d_43 = QtGui.QHBoxLayout()
        self.exe_d_43.setObjectName(_fromUtf8("exe_d_43"))
        self.label_82 = QtGui.QLabel(self.Registers)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.label_82.setFont(font)
        self.label_82.setObjectName(_fromUtf8("label_82"))
        self.exe_d_43.addWidget(self.label_82)
        self.register24 = QtGui.QLabel(self.Registers)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.register24.setFont(font)
        self.register24.setText(_fromUtf8(""))
        self.register24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.register24.setObjectName(_fromUtf8("register24"))
        self.exe_d_43.addWidget(self.register24)
        self.horizontalLayout_19.addLayout(self.exe_d_43)
        self.gridLayout_6.addLayout(self.horizontalLayout_19, 8, 0, 1, 1)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.exe_d_18 = QtGui.QHBoxLayout()
        self.exe_d_18.setObjectName(_fromUtf8("exe_d_18"))
        self.label_57 = QtGui.QLabel(self.Registers)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.label_57.setFont(font)
        self.label_57.setObjectName(_fromUtf8("label_57"))
        self.exe_d_18.addWidget(self.label_57)
        self.register9 = QtGui.QLabel(self.Registers)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.register9.setFont(font)
        self.register9.setText(_fromUtf8(""))
        self.register9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.register9.setObjectName(_fromUtf8("register9"))
        self.exe_d_18.addWidget(self.register9)
        self.horizontalLayout_20.addLayout(self.exe_d_18)
        self.exe_d_44 = QtGui.QHBoxLayout()
        self.exe_d_44.setObjectName(_fromUtf8("exe_d_44"))
        self.label_83 = QtGui.QLabel(self.Registers)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.label_83.setFont(font)
        self.label_83.setObjectName(_fromUtf8("label_83"))
        self.exe_d_44.addWidget(self.label_83)
        self.register25 = QtGui.QLabel(self.Registers)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.register25.setFont(font)
        self.register25.setText(_fromUtf8(""))
        self.register25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.register25.setObjectName(_fromUtf8("register25"))
        self.exe_d_44.addWidget(self.register25)
        self.horizontalLayout_20.addLayout(self.exe_d_44)
        self.gridLayout_6.addLayout(self.horizontalLayout_20, 9, 0, 1, 1)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.exe_d_29 = QtGui.QHBoxLayout()
        self.exe_d_29.setObjectName(_fromUtf8("exe_d_29"))
        self.label_68 = QtGui.QLabel(self.Registers)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.label_68.setFont(font)
        self.label_68.setObjectName(_fromUtf8("label_68"))
        self.exe_d_29.addWidget(self.label_68)
        self.register10 = QtGui.QLabel(self.Registers)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.register10.setFont(font)
        self.register10.setText(_fromUtf8(""))
        self.register10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.register10.setObjectName(_fromUtf8("register10"))
        self.exe_d_29.addWidget(self.register10)
        self.horizontalLayout_21.addLayout(self.exe_d_29)
        self.exe_d_45 = QtGui.QHBoxLayout()
        self.exe_d_45.setObjectName(_fromUtf8("exe_d_45"))
        self.label_84 = QtGui.QLabel(self.Registers)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.label_84.setFont(font)
        self.label_84.setObjectName(_fromUtf8("label_84"))
        self.exe_d_45.addWidget(self.label_84)
        self.register26 = QtGui.QLabel(self.Registers)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.register26.setFont(font)
        self.register26.setText(_fromUtf8(""))
        self.register26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.register26.setObjectName(_fromUtf8("register26"))
        self.exe_d_45.addWidget(self.register26)
        self.horizontalLayout_21.addLayout(self.exe_d_45)
        self.gridLayout_6.addLayout(self.horizontalLayout_21, 10, 0, 1, 1)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.exe_d_30 = QtGui.QHBoxLayout()
        self.exe_d_30.setObjectName(_fromUtf8("exe_d_30"))
        self.label_69 = QtGui.QLabel(self.Registers)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.label_69.setFont(font)
        self.label_69.setObjectName(_fromUtf8("label_69"))
        self.exe_d_30.addWidget(self.label_69)
        self.register11 = QtGui.QLabel(self.Registers)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.register11.setFont(font)
        self.register11.setText(_fromUtf8(""))
        self.register11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.register11.setObjectName(_fromUtf8("register11"))
        self.exe_d_30.addWidget(self.register11)
        self.horizontalLayout_22.addLayout(self.exe_d_30)
        self.exe_d_46 = QtGui.QHBoxLayout()
        self.exe_d_46.setObjectName(_fromUtf8("exe_d_46"))
        self.label_85 = QtGui.QLabel(self.Registers)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.label_85.setFont(font)
        self.label_85.setObjectName(_fromUtf8("label_85"))
        self.exe_d_46.addWidget(self.label_85)
        self.register27 = QtGui.QLabel(self.Registers)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.register27.setFont(font)
        self.register27.setText(_fromUtf8(""))
        self.register27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.register27.setObjectName(_fromUtf8("register27"))
        self.exe_d_46.addWidget(self.register27)
        self.horizontalLayout_22.addLayout(self.exe_d_46)
        self.gridLayout_6.addLayout(self.horizontalLayout_22, 11, 0, 1, 1)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.exe_d_31 = QtGui.QHBoxLayout()
        self.exe_d_31.setObjectName(_fromUtf8("exe_d_31"))
        self.label_70 = QtGui.QLabel(self.Registers)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.label_70.setFont(font)
        self.label_70.setObjectName(_fromUtf8("label_70"))
        self.exe_d_31.addWidget(self.label_70)
        self.register12 = QtGui.QLabel(self.Registers)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.register12.setFont(font)
        self.register12.setText(_fromUtf8(""))
        self.register12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.register12.setObjectName(_fromUtf8("register12"))
        self.exe_d_31.addWidget(self.register12)
        self.horizontalLayout_23.addLayout(self.exe_d_31)
        self.exe_d_47 = QtGui.QHBoxLayout()
        self.exe_d_47.setObjectName(_fromUtf8("exe_d_47"))
        self.label_86 = QtGui.QLabel(self.Registers)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.label_86.setFont(font)
        self.label_86.setObjectName(_fromUtf8("label_86"))
        self.exe_d_47.addWidget(self.label_86)
        self.register28 = QtGui.QLabel(self.Registers)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.register28.setFont(font)
        self.register28.setText(_fromUtf8(""))
        self.register28.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.register28.setObjectName(_fromUtf8("register28"))
        self.exe_d_47.addWidget(self.register28)
        self.horizontalLayout_23.addLayout(self.exe_d_47)
        self.gridLayout_6.addLayout(self.horizontalLayout_23, 12, 0, 1, 1)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.exe_d_32 = QtGui.QHBoxLayout()
        self.exe_d_32.setObjectName(_fromUtf8("exe_d_32"))
        self.label_71 = QtGui.QLabel(self.Registers)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.label_71.setFont(font)
        self.label_71.setObjectName(_fromUtf8("label_71"))
        self.exe_d_32.addWidget(self.label_71)
        self.register13 = QtGui.QLabel(self.Registers)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.register13.setFont(font)
        self.register13.setText(_fromUtf8(""))
        self.register13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.register13.setObjectName(_fromUtf8("register13"))
        self.exe_d_32.addWidget(self.register13)
        self.horizontalLayout_24.addLayout(self.exe_d_32)
        self.exe_d_48 = QtGui.QHBoxLayout()
        self.exe_d_48.setObjectName(_fromUtf8("exe_d_48"))
        self.label_87 = QtGui.QLabel(self.Registers)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.label_87.setFont(font)
        self.label_87.setObjectName(_fromUtf8("label_87"))
        self.exe_d_48.addWidget(self.label_87)
        self.register29 = QtGui.QLabel(self.Registers)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.register29.setFont(font)
        self.register29.setText(_fromUtf8(""))
        self.register29.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.register29.setObjectName(_fromUtf8("register29"))
        self.exe_d_48.addWidget(self.register29)
        self.horizontalLayout_24.addLayout(self.exe_d_48)
        self.gridLayout_6.addLayout(self.horizontalLayout_24, 13, 0, 1, 1)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.exe_d_35 = QtGui.QHBoxLayout()
        self.exe_d_35.setObjectName(_fromUtf8("exe_d_35"))
        self.label_74 = QtGui.QLabel(self.Registers)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.label_74.setFont(font)
        self.label_74.setObjectName(_fromUtf8("label_74"))
        self.exe_d_35.addWidget(self.label_74)
        self.register14 = QtGui.QLabel(self.Registers)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.register14.setFont(font)
        self.register14.setText(_fromUtf8(""))
        self.register14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.register14.setObjectName(_fromUtf8("register14"))
        self.exe_d_35.addWidget(self.register14)
        self.horizontalLayout_25.addLayout(self.exe_d_35)
        self.exe_d_49 = QtGui.QHBoxLayout()
        self.exe_d_49.setObjectName(_fromUtf8("exe_d_49"))
        self.label_88 = QtGui.QLabel(self.Registers)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.label_88.setFont(font)
        self.label_88.setObjectName(_fromUtf8("label_88"))
        self.exe_d_49.addWidget(self.label_88)
        self.register30 = QtGui.QLabel(self.Registers)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.register30.setFont(font)
        self.register30.setText(_fromUtf8(""))
        self.register30.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.register30.setObjectName(_fromUtf8("register30"))
        self.exe_d_49.addWidget(self.register30)
        self.horizontalLayout_25.addLayout(self.exe_d_49)
        self.gridLayout_6.addLayout(self.horizontalLayout_25, 14, 0, 1, 1)
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.exe_d_33 = QtGui.QHBoxLayout()
        self.exe_d_33.setObjectName(_fromUtf8("exe_d_33"))
        self.label_72 = QtGui.QLabel(self.Registers)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.label_72.setFont(font)
        self.label_72.setObjectName(_fromUtf8("label_72"))
        self.exe_d_33.addWidget(self.label_72)
        self.register15 = QtGui.QLabel(self.Registers)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.register15.setFont(font)
        self.register15.setText(_fromUtf8(""))
        self.register15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.register15.setObjectName(_fromUtf8("register15"))
        self.exe_d_33.addWidget(self.register15)
        self.horizontalLayout_26.addLayout(self.exe_d_33)
        self.exe_d_50 = QtGui.QHBoxLayout()
        self.exe_d_50.setObjectName(_fromUtf8("exe_d_50"))
        self.label_89 = QtGui.QLabel(self.Registers)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.label_89.setFont(font)
        self.label_89.setObjectName(_fromUtf8("label_89"))
        self.exe_d_50.addWidget(self.label_89)
        self.register31 = QtGui.QLabel(self.Registers)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        self.register31.setFont(font)
        self.register31.setText(_fromUtf8(""))
        self.register31.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.register31.setObjectName(_fromUtf8("register31"))
        self.exe_d_50.addWidget(self.register31)
        self.horizontalLayout_26.addLayout(self.exe_d_50)
        self.gridLayout_6.addLayout(self.horizontalLayout_26, 15, 0, 1, 1)
        self.gridLayout_3.addWidget(self.Registers, 0, 1, 1, 1)

        self.retranslateUi(Pipeline_CPU)
        QtCore.QMetaObject.connectSlotsByName(Pipeline_CPU)

    def retranslateUi(self, Pipeline_CPU):
        Pipeline_CPU.setWindowTitle(_translate("Pipeline_CPU", "Dialog", None))
        self.label.setText(_translate("Pipeline_CPU", "请输入指令序列：", None))
        self.StartButton.setText(_translate("Pipeline_CPU", "开始", None))
        self.NextstepButton.setText(_translate("Pipeline_CPU", "下一步", None))
        self.ResetButton.setText(_translate("Pipeline_CPU", "重置", None))
        self.label_clk.setText(_translate("Pipeline_CPU", "时钟周期", None))
        self.IF_stage.setTitle(_translate("Pipeline_CPU", "IF", None))
        self.ID_stage.setTitle(_translate("Pipeline_CPU", "ID", None))
        self.EXE_stage.setTitle(_translate("Pipeline_CPU", "EXE", None))
        self.MEM_stage.setTitle(_translate("Pipeline_CPU", "MEM", None))
        self.WB_stage.setTitle(_translate("Pipeline_CPU", "WB", None))
        self.Registers.setTitle(_translate("Pipeline_CPU", "REGISTERS", None))

    def initialize(self, Pipeline_CPU):
        #IF_stage
        self.IF_instruction.setText('')
        self.label_8.setText(_translate("Pipeline_CPU", "PC", None))
        self.label_4.setText(_translate("Pipeline_CPU", "BTAKEN", None))
        self.label_5.setText(_translate("Pipeline_CPU", "WPC", None))
        self.label_6.setText(_translate("Pipeline_CPU", "WIR", None))
        self.label_13.setText(_translate("Pipeline_CPU", "IR", None))
        #ID_stage
        self.ID_instruction.setText('')
        self.label_7.setText(_translate("Pipeline_CPU", "d", None))
        self.label_10.setText(_translate("Pipeline_CPU", "A", None))
        self.label_11.setText(_translate("Pipeline_CPU", "B", None))
        self.label_12.setText(_translate("Pipeline_CPU", "I", None))
        self.label_14.setText(_translate("Pipeline_CPU", "SST", None))
        self.label_15.setText(_translate("Pipeline_CPU", "SEXT", None))
        self.label_18.setText(_translate("Pipeline_CPU", "~LOADDEPEN", None))
        self.label_29.setText(_translate("Pipeline_CPU", "ADEPEN", None))
        self.label_24.setText(_translate("Pipeline_CPU", "BDEPEN", None))
        self.label_30.setText(_translate("Pipeline_CPU", "ALUOP", None))
        self.label_26.setText(_translate("Pipeline_CPU", "QDEPEN", None))
        self.label_53.setText(_translate("Pipeline_CPU", "WZ", None))
        self.label_58.setText(_translate("Pipeline_CPU", "WMEM", None))
        self.label_59.setText(_translate("Pipeline_CPU", "SLD", None))
        self.label_60.setText(_translate("Pipeline_CPU", "WREG", None))
        self.label_61.setText(_translate("Pipeline_CPU", "SHIFT", None))
        #EXE_stage
        self.EXE_instruction.setText('')
        self.label_19.setText(_translate("Pipeline_CPU", "d", None))
        self.label_20.setText(_translate("Pipeline_CPU", "Z", None))
        self.label_21.setText(_translate("Pipeline_CPU", "R", None))
        self.label_22.setText(_translate("Pipeline_CPU", "S", None))
        self.label_23.setText(_translate("Pipeline_CPU", "ADEPEN", None))
        self.label_31.setText(_translate("Pipeline_CPU", "BDEPEN", None))
        self.label_33.setText(_translate("Pipeline_CPU", "QDEPEN", None))
        self.label_25.setText(_translate("Pipeline_CPU", "ALUOP", None))
        self.label_40.setText(_translate("Pipeline_CPU", "WZ", None))
        self.label_65.setText(_translate("Pipeline_CPU", "WMEM", None))
        self.label_64.setText(_translate("Pipeline_CPU", "SLD", None))
        self.label_63.setText(_translate("Pipeline_CPU", "WREG", None))
        #MEM_stage
        self.MEM_instruction.setText('')
        self.label_41.setText(_translate("Pipeline_CPU", "d", None))
        self.label_42.setText(_translate("Pipeline_CPU", "D", None))
        self.label_43.setText(_translate("Pipeline_CPU", "C", None))
        self.label_34.setText(_translate("Pipeline_CPU", "QDEPEN", None))
        self.label_44.setText(_translate("Pipeline_CPU", "WMEM", None))
        self.label_66.setText(_translate("Pipeline_CPU", "SLD", None))
        self.label_67.setText(_translate("Pipeline_CPU", "WREG", None))
        #WB_stage
        self.WB_instruction.setText('')
        self.label_46.setText(_translate("Pipeline_CPU", "SLD", None))
        self.label_47.setText(_translate("Pipeline_CPU", "WREG", None))
        #REGISTERS
        self.label_45.setText(_translate("Pipeline_CPU", "r0", None))
        self.label_48.setText(_translate("Pipeline_CPU", "r1", None))
        self.label_49.setText(_translate("Pipeline_CPU", "r2", None))
        self.label_50.setText(_translate("Pipeline_CPU", "r3", None))
        self.label_51.setText(_translate("Pipeline_CPU", "r4", None))
        self.label_52.setText(_translate("Pipeline_CPU", "r5", None))
        self.label_54.setText(_translate("Pipeline_CPU", "r6", None))
        self.label_55.setText(_translate("Pipeline_CPU", "r7", None))
        self.label_56.setText(_translate("Pipeline_CPU", "r8", None))
        self.label_57.setText(_translate("Pipeline_CPU", "r9", None))
        self.label_68.setText(_translate("Pipeline_CPU", "r10", None))
        self.label_69.setText(_translate("Pipeline_CPU", "r11", None))
        self.label_70.setText(_translate("Pipeline_CPU", "r12", None))
        self.label_71.setText(_translate("Pipeline_CPU", "r13", None))
        self.label_74.setText(_translate("Pipeline_CPU", "r14", None))
        self.label_72.setText(_translate("Pipeline_CPU", "r15", None))
        self.label_73.setText(_translate("Pipeline_CPU", "r16", None))
        self.label_75.setText(_translate("Pipeline_CPU", "r17", None))
        self.label_76.setText(_translate("Pipeline_CPU", "r18", None))
        self.label_77.setText(_translate("Pipeline_CPU", "r19", None))
        self.label_78.setText(_translate("Pipeline_CPU", "r20", None))
        self.label_79.setText(_translate("Pipeline_CPU", "r21", None))
        self.label_80.setText(_translate("Pipeline_CPU", "r22", None))
        self.label_81.setText(_translate("Pipeline_CPU", "r23", None))
        self.label_82.setText(_translate("Pipeline_CPU", "r24", None))
        self.label_83.setText(_translate("Pipeline_CPU", "r25", None))
        self.label_84.setText(_translate("Pipeline_CPU", "r26", None))
        self.label_85.setText(_translate("Pipeline_CPU", "r27", None))
        self.label_86.setText(_translate("Pipeline_CPU", "r28", None))
        self.label_87.setText(_translate("Pipeline_CPU", "r29", None))
        self.label_88.setText(_translate("Pipeline_CPU", "r30", None))
        self.label_89.setText(_translate("Pipeline_CPU", "r31", None))

import pipeline